version = 1

[merge]
require_automerge_label = true
method = "squash"
delete_branch_on_merge = true
optimistic_updates = true

[merge.automerge_dependencies]
versions = ["minor", "patch"]
usernames = ["dependabot"]