name: Setup
description: "Setup Node.js, pnpm and dependencies"

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
    - name: Install Dependencies
      run: pnpm i -r --frozen-lockfile
      shell: bash
    - name: Build
      run: pnpm build
      shell: bash