name: Check Bundle Size

on:
  push:
    branches: [master]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Build
        run: pnpm build
      - name: Run BundleMon
        run: ./node_modules/.bin/bundlemon
        env:
          CI_COMMIT_SHA: ${{github.event.pull_request.head.sha || github.sha}} # important!