name: Check Size

on:
  pull_request:
    branches:
      - main

jobs:
  check-size:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: size-limit-action
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}