name: Release

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Build
        run: pnpm build
      - name: Deploy Package
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: npx semantic-release
      - name: Set Git Config
        env:
          GIT_EMAIL: ${{secrets.GIT_EMAIL}}
        run: |
          git config --global user.email "$GIT_EMAIL"
          git config --global user.name "hiroki0525"
      - name: Deploy Examples
        run: pnpm deploy:examples