name: Test and deploy

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm
      - name: Install Dependencies
        run: npm ci --workspaces
      - name: Test
        run: |
          npm run test && npm run lint && npm run prettier
      - name: Build
        run: npm run build
      - name: Deploy
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: npx semantic-release
#          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
#          npm run deploy
