name: Test

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Test
        run: |
          pnpm t && pnpm lint && pnpm prettier
      - name: Build
        run: pnpm build