name: Test and deploy

on:
  push:
    branches:
      - '*'

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: |
          npm run test && npm run lint && npm run prettier
      - name: Build
        run: npm run build
      - name: size-limit-action
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy Package
        if: github.ref == 'refs/heads/main'
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: npx semantic-release
      - name: Set Git Config
        if: github.ref == 'refs/heads/main'
        env:
          GIT_EMAIL: ${{secrets.GIT_EMAIL}}
        run: |
          git config --global user.email "$GIT_EMAIL"
          git config --global user.name "hiroki0525"
      - name: Deploy Examples
        if: github.ref == 'refs/heads/main'
        run: npm run deploy:examples