name: Test

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Test
        run: |
          npm run test && npm run lint && npm run prettier
      - name: Build
        run: pnpm build